### ISSUE TITLE
New CLI

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [LivInTheLookingGlass/ManifoldMarketManager#31]
# import
Arguments:
- one of:
  - file.{json, yaml}
  - --stdin --{json,yaml}
- account

# create
- see above
- --queue-on-failure
- --queue

# scan
Arguments:
- --disable-all (default)
- --enable-all
- --enable-[scanner]
# run
Hopefully using the actual event loop
# edit [--json or --yaml or --repl]
The idea is to:
- if repl, open a repl to edit the market manually
- otherwise, dump market in import format to temp file
- open editor
- on close, if edited, try to "import" new market
# remove
Arguments:
- id
- --assume-yes (-y)
# list
Have options for various filters, verbosity of listings, format

**Comment by LivInTheLookingGlass** [comment]
Bounty market: https://manifold.markets/LivInTheLookingGlass/bounty-which-of-your-suggestions-wi

**Comment by LivInTheLookingGlass** [comment]
Geez, just the parsing for this is ~100 lines. Not even with help texts

**Comment by LivInTheLookingGlass** [comment]
This is a work in progress, so I'm not committing yet

```python
"""Runner script for ManifoldMarketManager.

Includes a variety of command line options which can be explored by invoking with the `--help` flag.

Note that the behavior of this runner script is not yet stable. Many changes are going to occur between its current
state and the desired production behavior. These changes include:

- [ ] Multiple Account Support
- [ ] Create markets using JSON
- [ ] Import markets using JSON
- [ ] Queue markets to be created in the future
- [ ] Run hooks on various Markets, ex: when they are
  - [ ] queued
  - [ ] created
  - [ ] resolved
  - [ ] cancelled
- [ ] Use an event loop (maybe asyncio) rather that a sleep loop
- [ ] Allow rules to store data in the db (and clean up after them)
"""

from __future__ import annotations

from argparse import ArgumentParser
from logging import DEBUG, INFO, basicConfig, getLogger
from os import getenv

from . import consts
from .application import (create_command, edit_command, import_command, list_command, loop_command,
                          quick_create_command, remove_command, run_command, scan_command)

# Enable logging
basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=(INFO if not getenv("DEBUG") else DEBUG),
    filename=getenv("LogFile"),
)
logger = getLogger(__name__)

main_parser = ArgumentParser()

main_parser.add_argument('-v', '--verbose', action='count', default=0)

subparsers = main_parser.add_subparsers()

import_parser = subparsers.add_parser('import')
import_parser.add_argument('account', action='store', type=str)
import_parser.add_argument('file', action='store', type=str, nargs='?')
import_parser.add_argument('--interactive', action='store_true')
group = import_parser.add_mutually_exclusive_group(required=False)
group.add_argument('--yaml', action='store_true')
group.add_argument('--json', action='store_true')
group.add_argument('--repl', action='store_true')
import_parser.set_defaults(func=import_command)
# TODO: add templates here

# must finish import_parser first
create_parser = subparsers.add_parser('create', parents=[import_parser], add_help=False)
create_parser.add_argument('--queue-if-no-funds', action='store_true')
create_parser.add_argument('--queue', action='store_true')
create_parser.set_defaults(func=create_command)

quick_create_parser = subparsers.add_parser('quick-create')
quick_create_parser.add_argument(
    'type', type=str,
    choices=["BINARY", "PSEUDO_NUMERIC", "FREE_RESPONSE", "MULTIPLE_CHOICE"]
)
quick_create_parser.add_argument('account', action='store', type=str)
quick_create_parser.add_argument('close-on', action='store', type=str)
quick_create_parser.add_argument(
    '--resolve-when', nargs=2, action='append',
    help="Should be a qualified rule name, followed by a JSON string of its initializers"
)
quick_create_parser.add_argument(
    '--resolve-to', nargs=2, action='append', required=True,
    help="Should be a qualified rule name, followed by a JSON string of its initializers"
)
quick_create_parser.add_argument('--notes', type=str, action='store', default='')
quick_create_parser.set_defaults(func=quick_create_command)

scan_parser = subparsers.add_parser('scan')
scan_parser.add_argument('--disable-all', action='store_false', dest='all_scanners', default=True)
for scanner in consts.AVAILABLE_SCANNERS:
    scan_parser.add_argument(
        f'--enable-{scanner.replace(".", "-")}', dest='scanners', action='append_const', const=scanner
    )
scan_parser.set_defaults(func=scan_command)

run_parser = subparsers.add_parser('run')
run_parser.add_argument('--disable-all', action='store_false', dest='all_scanners', default=True)
for scanner in consts.AVAILABLE_SCANNERS:
    run_parser.add_argument(f'--enable-{scanner}', dest='scanners', action='append_const', const=scanner)
run_parser.set_defaults(func=run_command)

loop_parser = subparsers.add_parser('loop', parents=[run_parser], add_help=False)
loop_parser.set_defaults(func=loop_command)

edit_parser = subparsers.add_parser('edit')
edit_parser.add_argument('id', nargs='+', type=str)
edit_parser.set_defaults(func=edit_command)

remove_parser = subparsers.add_parser('remove')
remove_parser.add_argument('id', nargs='+', type=str)
remove_parser.add_argument('--assume-yes', '-y', action='store_true')
remove_parser.set_defaults(func=remove_command)

list_parser = subparsers.add_parser('list')
list_parser.add_argument('--stats', action='store_true')
list_parser.set_defaults(func=list_command)

args = main_parser.parse_args()
exit(args.func(**vars(args)))
```

**Comment by LivInTheLookingGlass** [comment]
Okay, at the point where it is *probably* at feature parity. I have limited ability to test, but the only failure I've seen is that the MTG market got improperly loaded. Current complaints with this implementation:

- Needs a lot more help text
- The loop command should be an event-loop version
- list needs more levels of verbosity
- list needs actual statistics to print
- import, create and quick-create can't be made until #10
- edit won't be implemented for quite some time
- scan won't do anything until #11 

I guess I should make each of these into separate issues, then close this one?
